### ISSUE TITLE
전체 시간표 데이터를 뿌려주는 방식 변경

### ISSUE THREAD

**Issue by HyunseolKim** [GDG-SSU/deviewsched-backend#6]
전체 시간표 데이터를 뿌려줄때

Day1과 Day2를 각각 나눠서 뿌려줄수 있으면 좋겠습니다.

아래 스크린샷을 보시다시피 Day1을 누르면 Day1시간표만 밑에 리스트에 뿌려줄것이고,
Day2를 선택하면 Day2 시간표만 밑에 뿌려줄예정이어서요.

Day1과 Day2를 각각 받을 수 있으면 좋겠습니다.

{
 "days":[
     "tracks":[
        "sessions":[
       ]  
     ]
   ]
}

이렇게 가야할것같네요

**Comment by unstabler** [comment]
요청하신 대로 수정 완료하였습니다. :)
